DEBUG: True
LOG_LEVEL: INFO

REDIS_TO_SEND_RESULT:
    HOST: 127.0.0.1
    PORT: 6379
    DB: 0
    PASS: ~

MONGODB_TO_STORE_RESULT:
    HOST: DB_ADDRESS
    MAINDB: DB_NAME

FOREIGN_PROXIE:

EDITORAI_API:
EDITORAI_TOKEN:  
