DEBUG: True
LOG_LEVEL: INFO

REDIS_TO_SEND_RESULT:
    HOST: 127.0.0.1
    PORT: 6379
    DB: 0
    PASS: ~

MONGODB_TO_STORE_RESULT:
    HOST: mongodb://baoer:wscnwx@112.124.1.118:27017/
    MAINDB: newscrawler

FOREIGN_PROXIE: socks5://112.124.1.118:49999

EDITORAI_API: http://106.14.251.78
EDITORAI_TOKEN: QB8YnKO480h163vRD43b9CJJfKDK39eM